// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/oauth/callback.ts";
import * as $$$0 from "./loaders/oauth/start.ts";

const manifest = {
  "loaders": {
    "mcp-oauth-template/loaders/oauth/start.ts": $$$0,
  },
  "actions": {
    "mcp-oauth-template/actions/oauth/callback.ts": $$$$$$$$$0,
  },
  "name": "mcp-oauth-template",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
